apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-bot.fullname" . }}
  labels:
    {{- include "discord-bot.labels" . | nindent 4 }}
type: Opaque
data:
  BOT_SECRET: {{ .Values.bot.secret | b64enc }}
  METAR_TOKEN: {{ .Values.bot.metarToken | b64enc }}
  STATION_TOKEN: {{ .Values.bot.stationToken | b64enc }}
